Fixes some tiny typos and inconsistencies in Rust documentation
w3f/w3f-education pull request #64
Opened 2023-05-13 08:26 UTC by behradkhodayar

Thanks for all the great effort put into bringing this valuable document into life.

Just noticed some minor typos.

This PR fixes those.

2023-05-13 16:30 UTC, CrackTheCode016 requested changes
@behradkhodayar Thank you very much for this! I really appreciate it, and is always open for more feedback as it materializes further.  

Just make that change and I am happy to merge it.

2023-05-13 16:30 UTC, CrackTheCode016 commented on docs/Rust/section8/intro.md
> -- [Installing a crate](./installing-crate.md)
Please keep this order but change `sidebars.js` (located [here](https://github.com/behradkhodayar/w3f-education/blob/main/sidebars.js#LL269C8-L269C8)) to match this layout, as I changed the order slightly when I recorded the videos.  The layout should be:

- Defining & Reading cargo.toml
- Installing a crate
- Defining features for a crate
- Unit Tests in Rust

Again, thank you so much for this!

2023-05-14 07:36 UTC, behradkhodayar commented on docs/Rust/section8/intro.md
> -- [Installing a crate](./installing-crate.md)
Thanks for the prompt preview & response. Applied the changes [which of course I believe makes more sense contextually compared to the previous one].

Guess its ready.

Looking forward to great upcoming material :-)

2023-05-14 13:10 UTC, CrackTheCode016 approved these changes
@behradkhodayar thank you very much! 🎉

2023-05-14 13:10 UTC, merged

2023-05-14 13:59 UTC, behradkhodayar commented
I appreciate you assessing & merging quickly during the weekend🙏